routes/web.php
<?php
use App\Http\Controllers\FileController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('/file', 'FileController');

Route::post('/upload','FileController@store')->name('upload');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/File.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class File extends Model
{
    protected $fillable = 
    [
        'fileName',
        'mimeType',
        'size'
    ];
    
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/helpers.php
<?php // Code within app\Helpers\Helper.php

namespace App\Helpers;
use Illuminate\Support\Facades\Storage;

class Helper
{

     /**
     * Returns the folder size.
     *
     * @return boolean.
     */
    public static function getTotalFolderSize($folder = 'local')
    {
        $files_with_size = 0;
        $files = Storage::disk($folder)->files();
        foreach ($files as $key => $file) {
          $files_with_size += Storage::disk('local')->size($file);
        }

        return $files_with_size;
    }

     /**
     * Upload a file to the local folder.
     *
     * @return boolean.
     */

    public static function uploadFile($upload, $randFileName, $fileExt){
        
        return Storage::put($randFileName . '.' .  $fileExt, file_get_contents($upload));

    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/FileController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use \App\File;

class FileController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        //$files =  Storage::disk('public')->allFiles();
      /*  $folder_size = 0;
      //  dd(public_path());
        foreach( \File::allFiles(public_path('storage')) as $file)
        {
            $folder_size += $file->getSize();
        }

        $folder_size = number_format($folder_size / 1048576,2);
      */
        $files_with_size = 0;
        $files = Storage::disk('local')->files();
        foreach ($files as $key => $file) {
          //$files_with_size[$key]['name'] = $file;
          $files_with_size += Storage::disk('local')->size($file);
        }
      //  dd( $files );
        return view('files.index', [
            'files' =>  File::all(),
            'folder_size' => $files_with_size
        ]);
    }

  

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('files.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {


       // Max 1024kb for uploaded file.
       request()->validate([
            'upload' => 'required|file|max:1024',
        ]);
        

        $randFileName = strtoupper(md5(uniqid(rand(),true))); 


        $fileExt  = $request->file('upload')->getClientOriginalExtension();

        $filePath = Storage::put($randFileName . '.' .  $fileExt, file_get_contents($request->file('upload')));

        if(!$filePath){
            return redirect()->route('file.index')->with('error','File was not uploaded');
        }

        File::create([
            'fileName' => $randFileName . '.' . $fileExt ,
            'mimeType' => $request->file('upload')->getClientMimeType(),
            'size'     => $request->file('upload')->getClientSize()
        ]);
       
        return redirect()->route('file.index')->with('success','Image uploaded successfully');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

    public function show(File $file){
        return Storage::download($file->filename);

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(File $file)
    {
       // dd($file->filename);
        if(Storage::delete([$file->filename])){
            $file->delete();
            return redirect()->route('file.index')->with('success','The file was deleted successfully');

        }

        return redirect()->route('file.index')->with('success','The file was not deleted');

    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/files/create.blade.php
@extends('layouts.layout')

@section('content')

<div>
    <form method="post" id="frm" action="{{ route('upload') }}" files="true" enctype="multipart/form-data">
        {{ csrf_field() }}
        <label for="Archivo"><b>File: </b></label><input type="file" name="upload" required>
        <input type="submit" value="Upload file" >
    </form>
</div>
@endsection

resources/views/files/index.blade.php
@extends('layouts.layout')

@section('content')

<h1>File list</h1>

@if(!empty($files))
<div>
    <h1>Folder size: {{ $folder_size }} Kb </h1>
    @foreach ($files as $file )
    <h2>File details</h2>

    <ul class="">
        <li>Name: {{ $file->filename }}</li>
        <li>Type: {{ $file->mimeType }}</li>
        <li>Weight: {{ $file->size }} Kb</li>
 
        <li>File for <a href='/file/{{ $file->id }}'>download here</a></li>
        <li>Path file: storage/app/{{$file->filename}}</li>
        <li>
            <form action="/file/{{ $file->id }}" method='post'>  
                @method('DELETE')
                @csrf
                <button type='submit'>Delete file</button>
            </form>
        </li>
    </ul>    
    @endforeach
@else
<p>There are not any file yet, you can upload the <a href="{{ route('file.create') }}">first one here</a></p>
@endif
</div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/layout.blade.php
<!DOCTYPE html>
<head>
    <title>@yield('title')</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<style>
    .is-completed{ 
        text-decoration: line-through
    }

</style>
</head>
<body>

    <div class="container">
        @include('partials.nav')
        @include('messages.messages')

        @yield('content')
    </div>
 
</body>

</html>

resources/views/messages/messages.blade.php
@if ($message = Session::get('success'))
<div class="alert alert-success alert-block">
	<button type="button" class="close" data-dismiss="alert">×</button>	
        <strong>{{ $message }}</strong>
</div>
@endif
@if ($message = Session::get('error'))
<div class="alert alert-danger alert-block">
	<button type="button" class="close" data-dismiss="alert">×</button>	
        <strong>{{ $message }}</strong>
</div>
@endif


@if ($message = Session::get('warning'))
<div class="alert alert-warning alert-block">
	<button type="button" class="close" data-dismiss="alert">×</button>	
	<strong>{{ $message }}</strong>
</div>
@endif


@if ($message = Session::get('info'))
<div class="alert alert-info alert-block">
	<button type="button" class="close" data-dismiss="alert">×</button>	
	<strong>{{ $message }}</strong>
</div>
@endif


@if ($errors->any())
<div class="alert alert-danger">
	<button type="button" class="close" data-dismiss="alert">×</button>	
	Please check the form below for errors
</div>
@endif

resources/views/partials/errors.blade.php
@if($errors->any())
    <div class="notificaiton alert—check">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

resources/views/partials/nav.blade.php
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="http://homestead.test">
    
      <img src="http://masquebits.com/images/r0bertinski.jpg" width="112" height="28">

      
    </a>

    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <a class="navbar-item" href="/file" >
        Show files
      </a>

      <a class="navbar-item" href="/file/create" >
        New file
      </a>

     
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <a href="/register"  class="button is-primary">
            <strong>Sign up</strong>
          </a>
          <a href="/login" class="button is-light">
            Log in
          </a>
        </div>
      </div>
    </div>
  </div>
</nav>

resources/views/partials/tasks_list.blade.php
<!-- if the project has tasks -->
@if($project->tasks->count())
    @foreach($project->tasks as $task)
        <form method="POST" action="/file/{{ $task->id }}">
            @method('PATCH')
            @csrf
            <div class="form-check">
                
                <input class="form-check-input" type="checkbox" name="completed" onChange="this.form.submit()" {{ $task->completed ? 'checked' : '' }}> 

                <label class="form-check-label {{ $task->completed ? 'is-completed' : '' }}" for="completed" >{{ $task->title}}</label>
                <span>Type: {{ $task->type }}</span>
            </div>
        </form>
    @endforeach
@else
    <p>There are not any file at the moment, please <a href="/file/create" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">create the firts one here</a>  
@endif 